const axios = require("axios");
const Alert = require("./models/Alert");

const BASE_URL = "http://4.227.188.44:8000";

const seedSmrAlert = async (alertUid) => {
  try {
    // 1️⃣ Avoid duplicate SMR
    const alreadyDone = await Alert.findOne({
      uid: alertUid,
      "metadata.smrReport": { $exists: true },
    });

    if (alreadyDone) {
      console.log(`⏭ SMR skipped (already exists): ${alertUid}`);
      return alreadyDone;
    }

    // 2️⃣ Call SMR API
    const { data } = await axios.post(`${BASE_URL}/smr_report`, {
      uid: alertUid,
    });

    // 3️⃣ Update Alert
    const alert = await Alert.findOneAndUpdate(
      { uid: alertUid },
      {
        caseType: "SMR",
        status: "Active",

        activity: [
          {
            title: "SMR Analysis",
            details: data.summary || "SMR report generated",
          },
        ],

        activityNote: [
          {
            note:
              data.recommendation ||
              "Suspicious Matter Report generated by system",
          },
        ],

        metadata: {
          ...((await Alert.findOne({ uid: alertUid }))?.metadata || {}),
          smrReport: data,
          smrGeneratedAt: new Date(),
        },
      },
      { new: true }
    );

    console.log("✅ SMR stored:", alert.uid);
    return alert;
  } catch (error) {
    console.error(
      `❌ SMR Error (${alertUid}):`,
      error.response?.data || error.message
    );
    throw error;
  }
};

module.exports = seedSmrAlert;
