/**
 * Seed master Obligation Library (150+ obligations)
 * Run: node api/scripts/seedObligations.js
 */
require("dotenv").config({ path: "./config/config.env" });
const path = require("path");
const fs   = require("fs");
const mongoose = require("mongoose");
const { connectDB } = require("../config/db");
const ObligationLibrary = require("../models/ObligationLibrary");
require("colors");

// AML/CTF obligations from seed/obligations.json (AML-001 → INS-002)
const amlObligations = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, "../../seed/obligations.json"), "utf-8")
);

const obligations = [
  // ── GOVERNANCE (GOV) ──────────────────────────────────────────────────────
  { obligationId: "GOV-001", regulatorySource: "RG104 s912A(1)(a); Corporations Act",     category: "Governance",  description: "Provide financial services efficiently, honestly and fairly.",                                    applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Governance Policy Template",   controlRefs: ["CTRL_GOV_001", "CTRL_GOV_002"] },
  { obligationId: "GOV-002", regulatorySource: "RG104; Corporations Act",                 category: "Governance",  description: "Comply with financial services laws and licence conditions.",                                  applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Compliance Plan Template",      controlRefs: ["CTRL_GOV_001", "CTRL_GOV_006"] },
  { obligationId: "GOV-003", regulatorySource: "RG105.40-45",                             category: "Governance",  description: "Maintain organisational competence with adequate human resources.",                            applicableEntityTypes: ["All"],              applicableLicenses: ["Any"], applicableServices: ["Any"], policyTemplate: "Training and Supervision Policy" },
  { obligationId: "GOV-004", regulatorySource: "RG105.40-45",                             category: "Governance",  description: "Ensure responsible managers have appropriate knowledge, skills, and experience.",               applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Governance Policy Template",   controlRefs: ["CTRL_GOV_002", "CTRL_GOV_003"] },
  { obligationId: "GOV-005", regulatorySource: "RG104.89-100",                            category: "Governance",  description: "Maintain adequate financial, technological, and human resources.",                             applicableEntityTypes: ["All"],              applicableLicenses: ["Any"], applicableServices: ["Any"], policyTemplate: "Financial Resources Policy",   controlRefs: ["CTRL_GOV_001"] },
  { obligationId: "GOV-006", regulatorySource: "RG104.59-62",                             category: "Risk Management", description: "Maintain adequate risk management systems.",                                               applicableEntityTypes: ["All"],              applicableLicenses: ["Any"], applicableServices: ["Any"], policyTemplate: "Risk Management Framework",    controlRefs: ["CTRL_RA_001", "CTRL_GOV_004"] },
  { obligationId: "GOV-007", regulatorySource: "RG166.30",                                category: "Governance",  description: "Maintain solvency (assets exceed liabilities) at all times.",                                 applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Financial Resources Policy",   controlRefs: ["CTRL_GOV_001"] },
  { obligationId: "GOV-008", regulatorySource: "RG166.33",                                category: "Governance",  description: "Maintain sufficient liquidity to cover 12 months of expenses.",                                applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Financial Resources Policy" },
  { obligationId: "GOV-009", regulatorySource: "RG166.62",                                category: "Governance",  description: "Have financial statements audited annually and lodge with ASIC.",                              applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Compliance Plan Template",      controlRefs: ["CTRL_GOV_006"] },
  { obligationId: "GOV-010", regulatorySource: "RG166 App 2",                             category: "Governance",  description: "Maintain NTA requirements for responsible entities.",                                         applicableEntityTypes: ["RE Only"],          applicableLicenses: ["AFSL_RE"], applicableServices: ["Fund Management"] },
  { obligationId: "GOV-011", regulatorySource: "RG166 App 4",                             category: "Governance",  description: "Maintain NTA requirements for custodians ($10M / 10% of revenue).",                          applicableEntityTypes: ["Custodians"],       applicableLicenses: ["AFSL_RE"], applicableServices: ["Custody Services"] },
  { obligationId: "GOV-012", regulatorySource: "RG166.69",                                category: "Governance",  description: "Hold $50,000 surplus liquid funds when holding client money/property >$100,000.",             applicableEntityTypes: ["All"],              applicableLicenses: ["Any"], applicableServices: ["Client Money Handling"] },
  { obligationId: "GOV-013", regulatorySource: "RG126; RG104",                            category: "Insurance",   description: "Maintain adequate professional indemnity insurance covering all financial services.",          applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"] },
  { obligationId: "GOV-014", regulatorySource: "RG126.40-45",                             category: "Insurance",   description: "Maintain minimum PI cover of $2 million per claim and aggregate.",                            applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"] },
  { obligationId: "GOV-015", regulatorySource: "RG217",                                   category: "Governance",  description: "Directors and officers must exercise due care and diligence.",                                  applicableEntityTypes: ["All"],              applicableLicenses: ["Any"], applicableServices: ["Any"],  controlRefs: ["CTRL_GOV_002"] },
  { obligationId: "GOV-016", regulatorySource: "RG51",                                    category: "Governance",  description: "Comply with conditions of any ASIC relief instruments.",                                       applicableEntityTypes: ["All"],              applicableLicenses: ["Any"], applicableServices: ["Any"] },

  // ── CONFLICTS (CON) ───────────────────────────────────────────────────────
  { obligationId: "CON-001", regulatorySource: "RG181.16; s912A(1)(aa)",                  category: "Conflicts",   description: "Have adequate arrangements for managing conflicts of interest.",                               applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Conflicts of Interest Policy", controlRefs: ["CTRL_GOV_001"] },
  { obligationId: "CON-002", regulatorySource: "RG181.28",                                category: "Conflicts",   description: "Identify, assess, and implement appropriate responses to conflicts.",                         applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Conflicts of Interest Policy" },
  { obligationId: "CON-003", regulatorySource: "RG181.27",                                category: "Conflicts",   description: "Avoid conflicts that cannot be adequately managed through controls or disclosure.",            applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"], policyTemplate: "Conflicts of Interest Policy" },
  { obligationId: "CON-004", regulatorySource: "RG181.33",                                category: "Conflicts",   description: "Document conflicts management arrangements and maintain compliance records.",                   applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"] },
  { obligationId: "CON-005", regulatorySource: "RG246",                                   category: "Conflicts",   description: "Comply with conflicted and other banned remuneration rules.",                                  applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"] },

  // ── AML/CTF (AML) ─────────────────────────────────────────────────────────
  { obligationId: "AML-001", regulatorySource: "AML/CTF Act s3",                          category: "AML/CTF",     description: "Register with AUSTRAC as a reporting entity before providing designated services.",            applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], policyTemplate: "AML/CTF Program" },
  { obligationId: "AML-002", regulatorySource: "AML/CTF Act s82",                         category: "AML/CTF",     description: "Enrol with AUSTRAC and keep enrolment details up to date.",                                   applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-003", regulatorySource: "AML/CTF Act s84",                         category: "AML/CTF",     description: "Provide AUSTRAC with correct and complete enrolment information.",                             applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-004", regulatorySource: "AML/CTF Act s26C",                        category: "AML/CTF",     description: "Conduct a ML/TF risk assessment identifying and assessing risks faced when providing designated services.", applicableEntityTypes: ["All Reporting"], applicableLicenses: ["Any"], applicableServices: ["Any"], policyTemplate: "EWRA / Risk Assessment", riskCategory: "Governance", controlRefs: ["CTRL_GOV_008", "CTRL_RA_001"] },
  { obligationId: "AML-005", regulatorySource: "AML/CTF Act s27",                         category: "AML/CTF",     description: "Adopt and maintain an AML/CTF Program appropriate to the ML/TF risks faced.",                  applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], policyTemplate: "AML/CTF Program", controlRefs: ["CTRL_GOV_001"] },
  { obligationId: "AML-006", regulatorySource: "AML/CTF Act s27(4)",                      category: "AML/CTF",     description: "Appoint a designated AML/CTF Compliance Officer at management level.",                        applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_GOV_006"] },
  { obligationId: "AML-007", regulatorySource: "AML/CTF Act s27(4A)",                     category: "AML/CTF",     description: "Board must take responsibility for and approve the AML/CTF Program annually.",                  applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_GOV_002"] },
  { obligationId: "AML-008", regulatorySource: "AML/CTF Act s36",                         category: "AML/CTF",     description: "Include Part A (Governance) of the AML/CTF Program: risk assessment, policies, oversight.",     applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-009", regulatorySource: "AML/CTF Act s36A",                        category: "AML/CTF",     description: "Include Part B of AML/CTF Program: CDD procedures aligned to risk assessment.",                applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-010", regulatorySource: "AML/CTF Act s16-21",                      category: "CDD",         description: "Conduct initial Customer Due Diligence before providing designated services.",                  applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], riskCategory: "Customer Risk", defaultWeight: 30, controlRefs: ["CTRL_CDD_001", "CTRL_CDD_005"] },
  { obligationId: "AML-011", regulatorySource: "AML/CTF Act s22",                         category: "CDD",         description: "Apply Enhanced Customer Due Diligence for high-risk customers.",                               applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_CDD_016"] },
  { obligationId: "AML-012", regulatorySource: "AML/CTF Act s23",                         category: "CDD",         description: "Screen customers against PEP lists and apply enhanced measures for PEPs.",                     applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_CDD_008"] },
  { obligationId: "AML-013", regulatorySource: "AML/CTF Act s24",                         category: "CDD",         description: "Apply Simplified Due Diligence only where all conditions are met and risk is genuinely low.",   applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_CDD_017"] },
  { obligationId: "AML-014", regulatorySource: "AML/CTF Act s32",                         category: "AML/CTF",     description: "Conduct ongoing monitoring including ongoing CDD and transaction monitoring.",                  applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_CDD_014", "CTRL_TM_001"] },
  { obligationId: "AML-015", regulatorySource: "AML/CTF Act s41",                         category: "AML/CTF",     description: "Screen customers and transactions against sanctions lists (UN, OFAC, DFAT).",                   applicableEntityTypes: ["All Entities"],     applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_CDD_009"] },
  { obligationId: "AML-016", regulatorySource: "AML/CTF Act s43",                         category: "AML/CTF",     description: "Apply targeted financial sanctions — freeze assets of designated persons/entities.",             applicableEntityTypes: ["All Entities"],     applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-017", regulatorySource: "AML/CTF Act s45",                         category: "AML/CTF",     description: "Report to AUSTRAC if unable to perform CDD — consider not providing the service.",              applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-018", regulatorySource: "AML/CTF Act s46",                         category: "AML/CTF",     description: "Do not tip off customers about SMR filing or related investigations.",                         applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-019", regulatorySource: "AML/CTF Act s41A",                        category: "Reporting",   description: "Lodge Suspicious Matter Reports (SMRs) with AUSTRAC within 24 hours (terrorism) or 3 business days.", applicableEntityTypes: ["All Reporting"], applicableLicenses: ["Any"], applicableServices: ["Any"], policyTemplate: "SMR Policy", controlRefs: ["CTRL_RPT_001"] },
  { obligationId: "AML-020", regulatorySource: "AML/CTF Act s43A",                        category: "Reporting",   description: "Lodge Threshold Transaction Reports (TTRs) for cash transactions ≥$10,000.",                   applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_RPT_002"] },
  { obligationId: "AML-021", regulatorySource: "AML/CTF Act s49",                         category: "AML/CTF",     description: "Conduct independent review of the AML/CTF Program at least every 3 years.",                    applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_GOV_011"] },
  { obligationId: "AML-022", regulatorySource: "AML/CTF Act s50",                         category: "Reporting",   description: "Lodge annual Compliance Report with AUSTRAC by 31 March each year.",                            applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-023", regulatorySource: "AML/CTF Act s51",                         category: "AML/CTF",     description: "Keep transaction records for at least 7 years.",                                              applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_RK_001"] },
  { obligationId: "AML-024", regulatorySource: "AML/CTF Act s112",                        category: "AML/CTF",     description: "Report International Funds Transfer Instructions (IFTIs) to AUSTRAC.",                         applicableEntityTypes: ["Tranche 1 - Banks & ADIs", "Tranche 1 - Remittance"], applicableLicenses: ["Any"], applicableServices: ["Remittance Services", "Banking (Deposits & Loans)"] },
  { obligationId: "AML-025", regulatorySource: "AML/CTF Rules 2025 s6",                   category: "AML/CTF",     description: "Apply Travel Rule for virtual asset transfers — include originator and beneficiary information.", applicableEntityTypes: ["Tranche 1 - VASP/DCEP"], applicableLicenses: ["AUSTRAC_VASP"], applicableServices: ["Virtual Asset Transfer"] },
  { obligationId: "AML-026", regulatorySource: "AML/CTF Act s34",                         category: "AML/CTF",     description: "Only rely on third parties for CDD with formal written arrangements and annual assessments.",    applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_CDD_018"] },
  { obligationId: "AML-027", regulatorySource: "AML/CTF Act s37",                         category: "Training",    description: "Provide AML/CTF training to all relevant employees at onboarding and periodically.",            applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], policyTemplate: "Training Policy", controlRefs: ["CTRL_TRN_001"] },
  { obligationId: "AML-028", regulatorySource: "AML/CTF Act s26",                         category: "AML/CTF",     description: "Manage ML/TF risks of products and services including new/emerging technologies.",              applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "AML-029", regulatorySource: "AML/CTF Act s38",                         category: "AML/CTF",     description: "Manage ML/TF risks from correspondent banking, agent, and outsourcing relationships.",          applicableEntityTypes: ["Tranche 1 - Banks & ADIs"], applicableLicenses: ["ADI"], applicableServices: ["Banking (Deposits & Loans)"] },
  { obligationId: "AML-030", regulatorySource: "AML/CTF Act — Tranche 2 s26C",            category: "AML/CTF",     description: "Tranche 2 entities must conduct risk assessment before 1 July 2026 commencement.",              applicableEntityTypes: ["Tranche 2"],        applicableLicenses: ["Any"], applicableServices: ["Any"], applicableDate: new Date("2026-07-01") },

  // ── CUSTODY (CUS) ─────────────────────────────────────────────────────────
  { obligationId: "CUS-001", regulatorySource: "RG133.83",                                category: "Custody",     description: "Written custody agreement before providing custodial services.",                               applicableEntityTypes: ["Custodians"],       applicableLicenses: ["AFSL_RE"], applicableServices: ["Custody Services"] },
  { obligationId: "CUS-002", regulatorySource: "RG133.92",                                category: "Custody",     description: "Segregate client assets from the custodian's own assets at all times.",                       applicableEntityTypes: ["Custodians"],       applicableLicenses: ["AFSL_RE"], applicableServices: ["Custody Services"] },
  { obligationId: "CUS-003", regulatorySource: "RG133.94",                                category: "Custody",     description: "Maintain complete and accurate records of all client holdings.",                               applicableEntityTypes: ["Custodians"],       applicableLicenses: ["AFSL_RE"], applicableServices: ["Custody Services"] },
  { obligationId: "CUS-004", regulatorySource: "RG133.100",                               category: "Custody",     description: "Reconcile client assets at least monthly.",                                                   applicableEntityTypes: ["Custodians"],       applicableLicenses: ["AFSL_RE"], applicableServices: ["Custody Services"] },
  { obligationId: "CUS-005", regulatorySource: "RG133.110",                               category: "Custody",     description: "Hold client money in trust accounts — not commingle with own funds.",                         applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Client Money Handling"] },

  // ── REPORTING (RPT) ───────────────────────────────────────────────────────
  { obligationId: "RPT-001", regulatorySource: "RG78; Corporations Act s912D",            category: "Reporting",   description: "Lodge breach reports with ASIC within 30 days of becoming aware.",                             applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"] },
  { obligationId: "RPT-002", regulatorySource: "RG271",                                   category: "Reporting",   description: "Maintain internal dispute resolution process compliant with RG 271 standards.",               applicableEntityTypes: ["All"],              applicableLicenses: ["Any"], applicableServices: ["Any"] },
  { obligationId: "RPT-003", regulatorySource: "RG165",                                   category: "Reporting",   description: "Be a member of AFCA for external dispute resolution.",                                        applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"] },
  { obligationId: "RPT-004", regulatorySource: "RG256",                                   category: "Reporting",   description: "Conduct client review and remediation programmes where required.",                             applicableEntityTypes: ["All AFSL Holders"], applicableLicenses: ["AFSL"], applicableServices: ["Any"] },
  { obligationId: "RPT-005", regulatorySource: "AML/CTF Act s41A",                        category: "Reporting",   description: "File Suspicious Matter Reports to AUSTRAC within prescribed timeframes.",                      applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_RPT_001"] },
  { obligationId: "RPT-006", regulatorySource: "AML/CTF Act s43A",                        category: "Reporting",   description: "File Threshold Transaction Reports for cash transactions ≥$10,000.",                          applicableEntityTypes: ["All Reporting"],    applicableLicenses: ["Any"], applicableServices: ["Any"], controlRefs: ["CTRL_RPT_002"] },
];

async function seed() {
  await connectDB();
  console.log("Connected to MongoDB");

  const allObligations = [...obligations, ...amlObligations];
  let inserted = 0, updated = 0, errors = 0;
  for (const ob of allObligations) {
    try {
      const result = await ObligationLibrary.findOneAndUpdate(
        { obligationId: ob.obligationId },
        ob,
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
      result ? updated++ : inserted++;
    } catch (err) {
      console.error(`Error seeding ${ob.obligationId}:`, err.message);
      errors++;
    }
  }
  console.log(`✓ Obligations seeded: ${inserted + updated} records (${errors} errors)`);
  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => { console.error(err); process.exit(1); });
